name: Preview Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.0.0

        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm Stuff
        run: npm install -D --save autoprefixer && npm install -D --save postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.5
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build Site
        run: hugo -t docsy -d public --gc --minify --cleanDestinationDir

      - name: Create SSH Key
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.DOCSBUILD_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sed -i -e "s#\\\\n#\n#g" ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Rsync Push
        run: |
          rsync -rvza -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" public/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.PR_REMOTE_TARGET }}pull-request-${{ github.event.number }}

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "A preview with your changes can be found at https://docs.ixsystems.com/PRs/pull-request-${{ github.event.number }}"
          check_for_duplicate_msg: true