name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Master
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Checkout Submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install npm stuff
        run: npm install -D --save autoprefixer && npm install -D --save postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.5
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build Site
        run: env HUGO_ENV="production" hugo -t docsy -d public --gc --minify --cleanDestinationDir

      - name: Create SSH Key
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.DOCSBUILD_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sed -i -e "s#\\\\n#\n#g" ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Rsync Push
        run: |
          rsync -rvza -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" public ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.PUBLISH_REMOTE_TARGET }}
