name: Preview Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.0.0

        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm Stuff
        run: npm install -D --save autoprefixer && npm install -D --save postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.5
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build Site
        run: hugo -t docsy -d public --gc --minify --cleanDestinationDir

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pull-request-${{ github.event.number }}-artifacts
          path: public/

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "A preview with your changes can be found at https://docs.ixsystems.com/PRs/pull-request-${{ github.event.number }}"
          check_for_duplicate_msg: true